### ISSUE TITLE
Consigo instalar via Composer?

### ISSUE THREAD

**Issue by JandersonFB** [sounoob/pagseguro-php-sdk#13]
Bom dia, preciso instalar via composer, tem essa opção ?

**Comment by grolandao** [comment]
Sim tem como fazer a instalação via composer somente inserir 

"require" : {
      "sounoob/pagseguro" : "*"
  },
  "minimum-stability": "dev"

Em seu composer.json

**Comment by grolandao** [comment]
"require" : {
      "sounoob/pagseguro" : "^1.0"
}
