### ISSUE TITLE
O projeto ainda está ativo?

### ISSUE THREAD

**Issue by cacacobra** [sounoob/pagseguro-php-sdk#14]
Olá! Quero usar esse projeto em um serviço, ele está maduro e confiável? 

Se sim, poderei estar colaborando ativamente em melhorias ao mesmo tempo que implemento em meu projeto.

**Comment by Sena** [comment]
Estive sem tempo nos últimos dias, voltarei a postar. Já existe gente usando para valer isso, para saber se está confiável é necessário feedback de vocês.

Toda ajuda é válida. Aceitamos sua ajuda.

**Comment by cacacobra** [comment]
Resolvi arriscar e implementei em um projeto, e pelo menos o que eu usei, que foi a venda e o retorno automático, está tudo ok.

A única observação seria organizar melhor os exemplos, ter uma documentação melhor, pra mim não foi problema pois todas as dúvidas eu tirei olhando diretamente as classes e entendo os códigos, mas para alguém menos experiente talvez confunda um pouco.

Mas, de um modo geral sua biblioteca está ótima, os Sources Codes estão fáceis de entender, diretos ao ponto. Bem pra Noob entender mesmo. rs

Obrigado por compartilhar este projeto com a comunidade.
