### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by jardimfelipe** [sounoob/pagseguro-php-sdk#15]
Alguém já usou isso com Woocommerce? Minha ideia vai ser usar isso e tentar fazer uma emissão de boletos mensalmente, para uma assinatura

**Comment by Matheus-Perez** [comment]
eu usei, so dei uma alterada de acordo com a minha necessidade

**Comment by Sena** [comment]
Cara, é um SDK, você vai ter que programar para incluir isso lá. Se voCê manjar de Woocommerce é simples, se você não manjar ai não será tão simples assim.
