### ISSUE TITLE
Problema ao rodar em produção

### ISSUE THREAD

**Issue by cacacobra** [sounoob/pagseguro-php-sdk#16]
Usei a lib para integrar a um sistema que estou fazendo, e testei todo em Sandbox, quando fui alterar para produção, estou recebendo o erro "Unauthorized".

Conferi o Token, mudei o método para  "Config::setProduction();" e sempre me retorna o erro abaixo;

Fatal error: Uncaught Exception: E-mail or token is invalid in this environment: Sandobx in(...)

Estranho é que o erro retornado não está me retornando o "Enviroment" correto.

Onde eu estou errando? Lembrando que no Sandbox funciona corretamente.

**Comment by cacacobra** [comment]
Fiz uma coisa bem tosca aqui, me perdoem de ante mão. Mas funcionou, mas ainda vale a pergunta caso eu esteja falando asneira.

Basicamente eu deixei apenas as URLs de produção, pois percebi que só estava direcionando pra Sandbox e claro eu estava recebendo o erro "Unauthorized". Então deve ter algum BUG no "Config::setProduction();".

`<?php

/**
 * Class URL
 */
class URL
{
    /**
     * @return string
     */
    public static function getWs()
    {
        #return Config::isSandbox() ? 'https://ws.sandbox.pagseguro.uol.com.br/' : 'https://ws.pagseguro.uol.com.br/';
        return Config::isSandbox() ? 'https://ws.pagseguro.uol.com.br/' : 'https://ws.pagseguro.uol.com.br/';
    }

    /**
     * @return string
     */
    public static function getPage()
    {
        #return Config::isSandbox() ? 'https://sandbox.pagseguro.uol.com.br/' : 'https://pagseguro.uol.com.br/';
        return Config::isSandbox() ? 'https://pagseguro.uol.com.br/' : 'https://pagseguro.uol.com.br/';
    }

    /**
     * @return string
     */
    public static function getStc()
    {
        #return Config::isSandbox() ? 'https://stc.sandbox.pagseguro.uol.com.br/' : 'https://stc.pagseguro.uol.com.br/';
        return Config::isSandbox() ? 'https://stc.pagseguro.uol.com.br/' : 'https://stc.pagseguro.uol.com.br/';
    }
}
`

**Comment by Sena** [comment]
setAccountCredentials(). o último parametro muda o ambiente. Se você chamar essa rotina ela pode mudar o ambiente para você. Pode ser isso que estava ocorrendo.

**Comment by cacacobra** [comment]
Puxa vida, era isso mesmo, nubei geral mesmo. 

Só uma observação. Isso me parece meio redundante chamar o "Config::setProduction()" e mesmo assim ter que setar o parâmetro no "setAccountCredentials".

Seria interessante unificar isso, pra evitar nubisses como a minha rs.

**Comment by Sena** [comment]
Vou melhorar esse fluxo no futuro, vlw pela dica.
