### ISSUE TITLE
posso usar em projeto yii2?

### ISSUE THREAD

**Issue by marcelowu** [sounoob/pagseguro-php-sdk#18]
posso usar em projeto yii2?

**Comment by Sena** [comment]
use meu filho, use.

**Comment by marcelowu** [comment]
fiz um teste ta funcionando, mas o boleto apareceu erro meu chefe, q acontece..
Fatal error: Uncaught Exception: API is not available in sandbox environment
pagseguro-php-sdk-master\source\Boleto.php:229

**Comment by Sena** [comment]
Não tem sandbox para API de boletos.

**Comment by marcelowu** [comment]
ah. entendi.vlw
