### ISSUE TITLE
Erro na API de Boletos

### ISSUE THREAD

**Issue by leobaiano** [sounoob/pagseguro-php-sdk#19]
Estou tentando utilizar a API de boletos mas o retorno que estou recebendo é sempre

```
stdClass Object ( [timestamp] => 2018-08-08T20:40:39.598+0000 [status] => 500 [error] => Internal Server Error [exception] => org.springframework.dao.IncorrectResultSizeDataAccessException [message] => result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements [path] => /recurring-payment/boletos )
```
Inicialmente tentei enviar um post com o json sem utilizar nenhuma biblioteca e recebi este erro, então decidi usar o SDK do pagseguro e por fim utilizei este aqui e nas 3 tentativas recebo o mesmo erro, não acho que estou enviando informações incorretas porque quando mando algum dado incorreto ou deixo de enviar um dado obrigatório o retorno vem com uma mensagem bem direta.

Escrevo essa issue na esperança de que possam me ajudar a descobrir qual o problema.

**Comment by Sena** [comment]
Rodando o arquivo de exemplo sem alterar nada, ele retorna esse erro também? Dependenod pode ser algum dado especifico que você inseriu e a API do PagSeguro bugou ao tratar aquele dado.

**Comment by Sena** [comment]
Fechado por falta de interatividade e falta de elementos para reprodução do erro.
