### ISSUE TITLE
API Boleto retorna Exceção: API is not available in sandbox environment

### ISSUE THREAD

**Issue by AlaerteGabriel** [sounoob/pagseguro-php-sdk#20]
Olá caros amigos e colegas de profissão!

Estou tentando os testes para boleto, entretanto de acordo com a exceção: "API is not available in sandbox environment" não poderei testar via sandbox... ?

Eu fiz uma integração com a API deles, porém não há como alterar a data de vencimento nem descrição. Alguém tem uma luz ?

**Comment by grolandao** [comment]
Olá infelizmente a API de boleto do pagseguro ainda não tem sandbox.

**Comment by AlaerteGabriel** [comment]
Olá! Estranho, eu fiz a integração com a API deles, a pagseguro-php-sdk e funciona, só o boleto que não gera com o link de retorno, mais registra o boleto na sandbox de boa. Entretanto não tive a liberdade de personalizar a descrição, instrução e data de vencimento.

**Comment by Sena** [comment]
Lá funciona a API de checkout transparente com opção de boleto. API boletos é outra coisa.
Por isso que voCê não conseguiu alterar detalhes do boleto, porque não é a API de boletos. 
É confuso eu sei, mas é o PagSeguro rsrs
