### ISSUE TITLE
Sounoob\pagseguro\Payment::setNotificationURL() não disponível

### ISSUE THREAD

**Issue by legle** [sounoob/pagseguro-php-sdk#24]
este método da classe payment não está disponível. é possível adicionar?

**Comment by Sena** [comment]
Fez a instalação conforme o [README.md](https://github.com/sounoob/pagseguro-php-sdk/blob/master/README.md) ?

Se sim, qual erro exato está ocorrendo? E qual das duas formas de instalação você utilizou?

**Comment by legle** [comment]
Olá!

Sim eu instalei conforme o arquivo readme.md e tudo funciona perfeitamente. o problema foi percebido quando tentei usar o método Sounoob\pagseguro\Payment::setNotificationURL(); e recebí o aviso de que ele não existia.

localmente resolvi o problema copiando o respectivo método do script para gerar boletos e colando no script mencionado no título da issue. o que resolveu o meu problema, mas gostaria de ver isso resolvido para todos os usuários.

Se preferir posso fazer um pull request com a alteração que fiz localmente, pois resolveu o problema e agora posso definir uma url de notificação nos meus scripts do pagseguro.

**Comment by legle** [comment]
desculpe, esqueci de mencionar que usei a instalação automática via composer.

**Comment by legle** [comment]
@Sena você sabe se esse problema chegou a ser corrigido? você precisa de mais alguma informação?

**Comment by Sena** [comment]
@legle desculpa, tive problemas pessoais, e acabei deixando o projeto abandonado.
Acabei de ver tudo aqui, você realmente tem razão, o método realmente não está lá. 
Me manda o pull request com a alteração que farei merge aqui, ai fica a contribuição no seu nome.

Tenho o código pronto para subir, qualquer coisa avisa que eu mesmo altero se for o caso.
