### ISSUE TITLE
Sandbox ou Produção

### ISSUE THREAD

**Issue by eborguezao** [sounoob/pagseguro-php-sdk#26]
Nos exemplos disponíveis não encontrei como informar ao código se é modo sandbox ou produção, como que faço isso?

**Comment by Sena** [comment]
Depois de passar as credenciais, use o setSandbox ou setProduction para forçar um ambiente.
Mas essa configuração é opcional, já que o SDK pode "descobrir" qual ambiente é, por si só.
```
//Envia email e token
\Sounoob\pagseguro\config\Config::setAccountCredentials('seu@email.com.br', 'BD65179DCD806314A77B774DF6148CA9');
//Informa de forma explicita que é sandbox.
\Sounoob\pagseguro\config\Config::setSandbox();
//Informa de forma explicita que é produção.
\Sounoob\pagseguro\config\Config::setProduction();
```
