### ISSUE TITLE
Trocar setShippingType por metodos mais declarativos

### ISSUE THREAD

**Issue by Sena** [sounoob/pagseguro-php-sdk#3]
Esperar o noob lembrar quando usar o 1, 2 ou 3, pode ser muita coisa.

Talvez, algo como os exemplos abaixo ajudasse um pouco mais.

`$this->setShippingTypePAC(); //$this->setShippingType(1);`
`$this->setShippingTypeSedex(); //$this->setShippingType(2);`
`$this->setShippingTypeOther(); //$this->setShippingType(3);`

@grolandao o que acha?

**Comment by grolandao** [comment]
Acho valido, essa alteração de fato facilita para uma "leitura" mais clara do código.

**Comment by Sena** [comment]
Show de bola, precisamos manter todos próximos métodos dessa forma.
