### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by Sena** [sounoob/pagseguro-php-sdk#5]
Será um bom momento termos namespaces? 
Dependendo do rumo do projeto poderá causar conflitos com o projeto de quem estiver usando.

**Comment by grolandao** [comment]
Seria interessante, porem dificil para um noob conseguir contribuir já que dificultaria a localização das funçoes e das classes.

**Comment by Sena** [comment]
Mas nem um namespace simples de um nivel?

**Comment by grolandao** [comment]
Um namespace simples de um nivel geralmente só é visto quando se começa a estudar orientação a objetos, uma pessoa que sabe somente o procedural, muito prvavelmente não saberia usar os namespace

**Comment by grolandao** [comment]
Então acha que mesmo assim seria viavel a inclusão de namespace?

**Comment by Sena** [comment]
Eu tenho certeza que sim, só não sei se agora é o melhor momento. @LeandroVCastro  o que acha? 
Lembrando da proposta inicial é manter o código o mais noob possivel, para qualquer idiota conseguir entender o que está ocorrendo.

**Comment by Sena** [comment]
@grolandao bora avançar com isso? Enviar ai os namespaces de uma forma simplificada?

**Comment by grolandao** [comment]
O que podemos fazer. Colocar os namespaces e criar um "Dicionario de namespaces" Indicando de onde estar sendo definido cada namespace

**Comment by geekcom** [comment]
olá pessoal, não acho que incluir namespaces na lib fugiria da idéia de ser simples de usar, a lib já usa composer, bastaria alterar o composer.json para usar namespace PSR4
